### PR TITLE
add redirects

### PR DESCRIPTION
**Pull request by ErinBecker**
Adds redirects for most commonly used links within instructor training materials.

### CODE REVIEW

**Comment by ErinBecker** [comment]
@jduckles Don't merge yet. Working out an issue.

**Comment by ErinBecker** [comment]
Not sure whether everything other than reference and index need to be in the _extras directory, but need to jump on my next plain. @maneesha @jduckles does one of you have time to test this?

**Comment by maneesha** [comment]
I'm not sure how to build this locally or do whatever else is needed to test.  Perhaps @jduckles  can help?

**Comment by jduckles** [comment]
@ErinBecker do you want this merged still?

**Comment by ErinBecker** [comment]
@jduckles - I need someone to check the formatting please. @maneesha and I have both tried to render this locally, but because of the redirects, it's difficult to tell exactly how it's working. Would you be able to see if this is working to redirect the second-level instructor-training links to the carpentries repo?

**Comment by jduckles** [comment]
I have never done anything with this repo before, so I'm not sure I'm going to be that helpful either. 

Can you give me some background what we're trying to accomplish with this PR?

**Comment by ErinBecker** [comment]
The problem is that after migrating the instructor-training repo from the swcarpentry organization to the carpentries organization, none of the links automatically redirected. 

[My previous PR](https://github.com/swcarpentry/swcarpentry.github.io/pull/2) put in a redirect for the index.md file, so swcarpentry.github.io/instructor-training now goes to carpentries.github.io/instructor-training.

However, the lower-level links do not redirect. For example:

http://swcarpentries.github.io/instructor-training/checkout/ does not go to http://carpentries.github.io/instructor-training/checkout/.

So @maneesha has been getting a lot of questions from people with broken links and has had to redirect them herself. This will also be a problem when we are transitioning other repos to the carpentries organization on GitHub (e.g. workshop templates). 

Tagging @pipitone as he was the one who pointed us toward the re-direct strategy and saved the main link! Maybe he'll have a suggestion for fixing the lower-level links as well.

**Comment by pipitone** [comment]
I guess you could employ the same style for the lower-level links, e.g. add a `checkout/index.html` file that redirects to `carpentries.github.io/instructor-training/checkout`. You'd need to do that for all of the folders (and possibly all of the pages if you wanted that granularity of redirection) in the old site. Rather than writing HTML, I see there is [a jekyll redirection module](https://help.github.com/articles/redirects-on-github-pages/) that would let you write these in files in markdown, for what that's worth.

Idea #2: (and probably worth doing either way) create a [custom 404](https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/) page that explains what has happened and redirects people to the new front page, so that all dead links lead somewhere sensible.

**Comment by ErinBecker** [comment]
Thanks @pipitone. The instructions for creating a custom 404 don't look too bad. I'll try to get that put together and we'll see what happens!

**Comment by maneesha** [comment]
This is super old and I doubt we have anyone who still has the swc links, but I'm going to merge it now just in case.  I don't think it should have any impact.

**Pull request merged**
