### PR TITLE
Use secure links everywhere.

### PR DESCRIPTION
**Pull request by QuLogic**
All of these are available over https, and most of them already redirect there, too.

### CODE REVIEW

**Comment by gvwilson** [comment]
Thanks for the PR - I don't think we use/update this repo at the moment (our website is in https://github.com/swcarpentry/website) - it was probably created as a placeholder.

**Comment by QuLogic** [comment]
Yes, I know; I'm not really sure why half of the files are even here, but the main point is to change the redirect so it goes to https://software-carpentry.org/ not http:.

**Comment by gvwilson** [comment]
I don't think this repo was ever completed - I should delete the whole 
thing.  If you'd like to check/fix stuff in the website repo, that would 
be very welcome.

**Comment by QuLogic** [comment]
The only thing that's really useful here is the `index.html` that redirects swcarpentry.github.io to software-carpentry.org.

**Comment by QuLogic** [comment]
The redirect is still not using https.

**Pull request closed without merging**
